### ISSUE TITLE
Suggestions & bugs

### ISSUE THREAD

**Issue by megabugman** [Descolada/UIAutomation#13]
hi, I just started using UIAViewer, looks really promising. 
1) I noticed when hovering over the UIAViewer window, clinking stuff may lead to to a critical error:
![critical](https://user-images.githubusercontent.com/17204819/178126208-eeeebf30-d7ea-4ccc-b41a-919fe2744fdb.png)
2a) When maximized "UlAutomation Element Properties" becomes small and "UlAutomation Element Pattems" becomes way to big.
2b) I miss an option to change & restore the size of the these two groups
3) The Position in Window/Control Info is not updated. To reproduce Start Capturing, select a window e.g. win calc, then move the calculator window. The Position edit control is not updated.
Cheers

**Comment by Descolada** [comment]
Hey! Thanks for the input!
1. I tried reproducing the error, but haven't succeeded so far. Please try the latest UIAViewer and if the problem persists also tell me you AHK version so I can try to reproduce
2. The groups can now be resized by dragging inbetween them. Maximizing will still cause some fields to become very large, but the program is not intended to be used maximized.
3. Position in Window/Control Info is now updated as well. Note that the properties/patterns might also not always be up-to-date, this is to save processing power and speed up the program. Clicking in the treeview updates all the fields, also when moving the mouse away and back to the element when live capturing.

**Comment by megabugman** [comment]
thanks for the quick reply.

1. cannot reproduce the issue
2. thank you!
3. thanks again!
