### ISSUE TITLE
UIA Tree Inspector list view incorrect caption

### ISSUE THREAD

**Issue by megabugman** [Descolada/UIAutomation#14]
1.  the list view caption "ID" shows the window handle instead of PID
![id](https://user-images.githubusercontent.com/17204819/178158509-c017a458-8b61-4864-8512-939e871e7c05.png)

2. please consider adding "The groups can now be resized by dragging inbetween them." as in UIAViewer.

**Comment by Descolada** [comment]
1. Yes, ID as in ahk_id as in hwnd. I used the same naming convention as WindowList.ahk. Process ID (PID) doesn't seem to be very useful in these cases anyway.
2. I'll consider it, but I wasn't planning on UIATreeInspector being a "thing". It was written as a one-off script to access hidden windows (which is in most cases not even necessary), nothing more, so I probably won't be supporting it much (though Git pull requests are always welcome)
