### ISSUE TITLE
Click on path to copy to Clipboard - visual feedback

### ISSUE THREAD

**Issue by megabugman** [Descolada/UIAutomation#15]
please consider adding some sort of visual feedback after copying the path to the clipboard , eg. like in vis2
![path](https://user-images.githubusercontent.com/17204819/178159541-c1b9fe59-58d4-4acb-ab84-c5f6edcb97bd.png)
cheers

**Comment by Descolada** [comment]
When you left/right click on the path, does it not show a tooltip ("Copied "path" to Clipboard!" message)?

**Comment by Descolada** [comment]
This was a bug in AHK, the incorrect positioning of the ToolTip was supposed to be fixed in [AHK version 1.1.34.00](https://www.autohotkey.com/docs/AHKL_ChangeLog.htm). Are you running an older version?
With the latest AHK version the ToolTip always appears where the click was made.

**Comment by megabugman** [comment]
you are right, i was using an old version 1.1.33.9
