### ISSUE TITLE
incorrect/missing name property

### ISSUE THREAD

**Issue by megabugman** [Descolada/UIAutomation#17]
the name property is incorrect/missing:
![name_property](https://user-images.githubusercontent.com/17204819/178164093-c3851683-aa28-4846-9573-c360b1e6d5be.png)
to fix you need to place a Text control before the Edit control, also see solution by lexikos, [here](https://www.autohotkey.com/boards/viewtopic.php?style=1&t=89984)

**Comment by megabugman** [comment]
name missing
![must_not_be_null](https://user-images.githubusercontent.com/17204819/178370497-18ab6167-1999-4031-a681-677e38122988.png)

**Comment by Descolada** [comment]
Names for edit elements are now fixed, but also list items have names with null. Any ideas on how to fix that?
