### ISSUE TITLE
show "Access is denied" error when unable to inspect elements

### ISSUE THREAD

**Issue by megabugman** [Descolada/UIAutomation#18]
when running a process like notepad as admin, capturing will not find any UIA Element Properties of notepad.
the same applies to inspect.exe so it's not a bug, but inspect shows an error message:

How found:	Mouse move (1402,689)
	hwnd=0x000000000010076A ??bit class="Edit" style=0x50200104 ex=0x0
------
Cannot get object from point:
[Error: FromPoint: hr=0xFFFFFFFF80070005 - Access is denied.]

**Comment by Descolada** [comment]
It will be fixed in the next version.
