### ISSUE TITLE
Get Element Property value e.g Name

### ISSUE THREAD

**Issue by tdalon** [Descolada/UIAutomation#20]
Hi Descolada.
I was looking for an Element found by its Id a way to get its Name Property.
I have tried: El.GetAttributeValue("Name") El._Get("Name"), El.Name

Finally looking at the Dump function I've found El.CurrentName returns the Element Name.

Is there a function I have missed to get the Properties e.g. returned by the Dump method in a easy way? Or shall one parse the Dump output for a property value?

**Comment by Descolada** [comment]
Element properties are mostly listed under class UIA_Element in the variable __properties. CurrentName is indeed the property to get the name, so element.CurrentName will work.

**Comment by tdalon** [comment]
I was expecting the property to be named as what we can see with the insight tool. It is a bit counterintuitive.

**Comment by Descolada** [comment]
I think todays update does what you mentioned: now element.Name should return the CurrentName, also properties that are not listed under UIA_Element class as properties are available, such as element.IsValuePatternAvailable
