### ISSUE TITLE
Continuation section too long

### ISSUE THREAD

**Issue by johnydyote** [Descolada/UIAutomation#22]
I get this error when try to compile a simple script to open a chrome window.

![image](https://user-images.githubusercontent.com/109248744/178838621-3ff9d4c5-2bed-4ed7-8571-4a1770472ee0.png)

**Comment by Descolada** [comment]
Hello, 
I am unable to reproduce the error. If you are using compression, try turning that off and try again. Otherwise please also provide your AHK and Windows versions.

**Comment by johnydyote** [comment]
This was an oversight from my side, i tried to save ahk the file by right click and save it rather than opening it and copy the contents and save it. 

Thats why it added additional HTML code to the file which failed to run. You can completely delete this report, as there is no actual issue. Sorry about the trouble.
