### ISSUE TITLE
AutomationEventHandler

### ISSUE THREAD

**Issue by tgdonovan** [Descolada/UIAutomation#24]
I thought I would take this off the main thread. This Didn't work.

UIA := UIA_Interface()
OutlookMainID := WinExist("ahk_exe outlook.exe")
elementMain := UIA.ElementFromHandle(OutlookMainID)
homeTab := elementMain.FindFirstByNameAndType("Home","TabItem")
handler := UIA_CreateEventHandler("TabItemSelectedEventHandler")
UIA.AddAutomationEventHandler(UIA_Enum.UIA_SelectionItem_ElementSelectedEventId, homeTab,,,handler) ; or if it doesn't work, try using elementMain here
OnExit("Cleanup")
return

Cleanup() {
    UIA_Interface().RemoveAllEventHandlers()
}

TabItemSelectedEventHandler(sender, event) {
    ToolTip, Selected!
}

As Accessibility Insights showed a Property ID for the event details it showed of 30079, I changed your enum to UIA_SelectionItemIsSelectedPropertyId (and also tried the absolute value of 30079, as realize the enum probably really isn't right).

The TabItemSelectedEventHandler doesn't get triggered. 

Is there a way to handle all events for an element, not just one, so I could then monitor events and work towards the right filter to monitor for.

Thanks for your help.

**Comment by Descolada** [comment]
Hello,
AFAIK it isn't possible to capture ALL events for a given element, but you can create a group event handler for multiple different events at once. 

Could you please attach a screenshot of Accessibility Insights, where it has captured the UIA_SelectionItem_ElementSelectedEventId event? Just because there is UIA_SelectionItemIsSelectedPropertyId doesn't mean it also triggers the corresponding event (it has to be specifically implemented by the program: for example Outlook 365 doesn't trigger it).

**Comment by tgdonovan** [comment]
Here is what I ask (although I realize the two SelectionItems aren’t triggering anything.

***@***.***

Move away from Home Tab
***@***.***

Select Home Tab

***@***.***

I have tried playing with AddPropertyChangedEventHandler, but haven’t been successful.

Thanks.

Tom Donovan

**Comment by Descolada** [comment]
It seems PropertyChangedEvent works. At the moment newValue will be set to "Invalid variant", this will be fixed in the next update of UIA_Interface...
```
#Include <UIA_Interface>

UIA := UIA_Interface()
OutlookMainID := WinExist("ahk_exe outlook.exe")
elementMain := UIA.ElementFromHandle(OutlookMainID)
homeTab := elementMain.FindFirstByNameAndType("Home","TabItem")
handler := UIA_CreateEventHandler("HomeTabSelected", "PropertyChanged")
UIA.AddPropertyChangedEventHandler(homeTab,,,handler, [UIA_Enum.UIA_SelectionItemIsSelectedPropertyId])
OnExit("Cleanup")
return
Cleanup() {
    UIA_Interface().RemoveAllEventHandlers()
}
HomeTabSelected(sender, propertyId, newValue) {
    ToolTip, % "Sender: " sender.Dump() 
        . "`nPropertyId: " propertyId
        . "`nNew value: " newValue
}
```

**Comment by tgdonovan** [comment]
That works.  Now that I see the code it seems understandable, but so much of this UIA seems to be non discoverable (at least to me).

I greatly appreciate your assistance.

Would you like me to add the final code to the main thread on the AutoHotKey Forum?

Tom Donovan

**Comment by Descolada** [comment]
Yeah, UIA is complex and wrapping it in AHK creates another layer of complexity... Though I am still thinking of ways to make this even easier :)

I edited my last post in the main thread, where I posted the working code.
