### ISSUE TITLE
Unable to run UIA Interface File in the system

### ISSUE THREAD

**Issue by sanjay-koppuravuri** [Descolada/UIAutomation#28]
Hi,

I have downloaded the library and tried to use that to create scripts but i got the following error:
![image](https://user-images.githubusercontent.com/118434904/202406858-d9640b39-b16a-4251-a5be-d54068975305.png)

ControlViewWalker[] {
Error: Expected assignment or class/method definition.
The program will exit.

Even Example files that are there in the library are not running in the system.

Please help me in resolving this issue.

**Comment by Descolada** [comment]
Hello,
Please post your AHK version. If you copied the files properly then I think you might be running a too old version of AHK v1. Note that this library doesn't work in AHK v2.

**Comment by sanjay-koppuravuri** [comment]
Hi Descolada,

My AHK Version is 1.1.13.01. Will this be fine?

**Comment by Descolada** [comment]
AHK 1.1.13.01 is a VERY old (like 8 years old) version and will not run this library. Uncountable features and bugfixes have been made in the meanwhile. I recommend updating to the latest version, it should fix your issue :)

**Comment by sanjay-koppuravuri** [comment]
Ok, I will update it and will try again.

Thanks Descolada
