### ISSUE TITLE
Running example script generates excessive warnings with #Warn directive enabled

### ISSUE THREAD

**Issue by TerraTech** [Descolada/UIAutomation#29]
AutoHotkey version: [1.1.35.00](https://www.autohotkey.com/docs/AHKL_ChangeLog.htm#v1.1.35.00)
_Also occurred in version: 1.1.34.01_

I was working on a script that enumerates Chrome tabs, and I always include the `#Warn` directive.

When I tried to run my script, there were a lot of warnings raised.

One of the really frustrating ones was:
```
Warning in #include file
"...\Lib\UIA_Interface.ahk"
This line will never execute due to Exit preceeding it.
[...]
---> 3870: {
```

I then tried to run one of your example scripts, with `#Warn` enabled, and it caused a lot of warnings as well.
https://github.com/Descolada/UIAutomation/blob/main/Examples/Example3_Calculator.ahk

There were several superfluous warnings in UIA_Browser.ahk, most of them where there is a `break` following a `return`
Lines: 143, 188, 223, 396

Are there any plans on making the UIAutomation library `#Warn` safe/compliant?

TIA!

**Comment by Descolada** [comment]
The latest update should fix the warnings. This involved a LOT of changes for both UIA_Interface and UIA_Browser, so please notify me here if you find any new bugs or warnings :)

**Comment by TerraTech** [comment]
Thank you Descolada for the `#Warn` fixes.

However there is one warning remaining within my script.

![image](https://user-images.githubusercontent.com/1118433/203868292-cd3ec09c-a276-4d52-a16b-fe091ccfe1db.png)

```AutoHotKey
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
#Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

#SingleInstance Force

#include <TT-AutoReload>
#include <TT-Lib>
#include <UIA_Browser>
#include <JSON>
#include <VD>
```

I have tried placing the `#include <UIA_Browser>` at the top and also at the bottom.  The `#include <UIA_Browser>`  will trigger the warning regardless of position.

If you need more context, please let me know.

**Comment by Descolada** [comment]
I'm not totally sure what is/was causing it, but try it with the new version (just updated). If it still happens then I do need more information: your AHK version; whether you updated both UIA_Interface AND UIA_Browser from GitHub; whether a simple script with just #include <UIA_Interface> and #include <UIA_Browser> causes it, or one of your other libraries needs to also be included (eg JSON).

**Comment by TerraTech** [comment]
I have confirmed that commit 4b70408502267ec0f5ae6d1b992220df1bb27791 has fixed the final `#Warn` false positive.

Thank you.
