### ISSUE TITLE
List items truncated

### ISSUE THREAD

**Issue by megabugman** [Descolada/UIAutomation#31]
applies as well to the items in the Match mode combo box:
![trucated](https://user-images.githubusercontent.com/17204819/209734211-48464198-8343-462d-ab66-16af6be7e7c0.jpg)

**Comment by megabugman** [comment]
I guess I need to clarify the issue. the combo box issue arises after resizing the UI:
![clarify](https://user-images.githubusercontent.com/17204819/209736286-a6d16d28-7258-460c-80a4-c6fb27d8f8a3.jpg)

**Comment by Descolada** [comment]
The resizing issues should be fixed by the latest update.

**Comment by megabugman** [comment]
Fixed but now there is another issue
![fixed_but](https://user-images.githubusercontent.com/17204819/209942109-50439a38-1256-446b-b47e-d8e230a98804.jpg)

**Comment by Descolada** [comment]
Fixed now as well.
