### ISSUE TITLE
UIA very slow with Firefox (with suggested fix)

### ISSUE THREAD

**Issue by enaaab460** [Descolada/UIAutomation#33]
Both ElementFromHandle and UIA_Mozilla() are much slower in firefox (version 109) than chrome (also version 109) for detecting page elements (especially if the page has alot of elements and also videos, and if other tabs are open). Finding a paragraph in mozilla would take 4000ms in mozilla and only 100 ms in Chrome. Interacting with a fullscreen videos takes 15000 to 20000ms (i really mean 15 to 20 seconds). I discovered the getmaindocumentelement() and it would reduce time to get text down to 1-2 seconds, but still interacting with videos or devtools takes 20 seconds or timesout altogether. I think the main problem is that Mozilla's tree is much larger than Chrome's, and accessess all tabs' elements not just the active one, and that getmaindocumentelement() many times gets the wrong tab, 

I tinkered around with getmaindocumentelement(), and once i changed it to the following, accessing a page's document became only 50 ms slower than Chrome (100ms chrome vs 150ms in firefox)

```
mycurrenttabElement() {
		return this.FindFirstBy("ControlType='Custom' AND IsOffscreen='0'",2)  ; findfirstby("AutomationId='panel-1-' AND IsOffscreen='0'",2,2) also works
;isoffscreen=0 is very important for this to work, and this is the  only element where it works (all document elements have isoffscreen=0,  and all nonactive automationidpanels have isoffscreen=1
	}

GetCurrentDocumentElement() {
		return this.mycurrenttabElement().findbypath("1.1")
	}
```

I understand that the original way is more thought out, but in my experience it is buggy.

Regarding the very slow devtools, i modified the JSexecute to look for the current tab onlynot the whole mozilla UIA window after a short sleep as follows:

```
JSExecute(js){
Send, {LCtrl up}{LAlt up}{LShift up}{RCtrl up}{RAlt up}{RShift up}
			Send, {ctrl down}{shift down}k{ctrl up}{shift up}
			this.mycurrenttabElement().findbypath("2.1.1").WaitElementExistByNameAndType("Switch to multi-line editor mode (Ctrl + B)", "Button")
			clipboard=js
                        send ^v{Enter}
			sleep 200
			Send, {ctrl down}{shift down}i{ctrl up}{shift up}
}

```
PS: I also figured out how to execute JS through the addressbar, but it requires adding a special bookmark to your own browser first. So in my file I added support for it.
![image](https://user-images.githubusercontent.com/34572749/214560490-7a57379f-7f1a-42a9-b8c2-3df2e6873075.png)

**Comment by Descolada** [comment]
Hello,
I don't use Firefox regularly, but I do try to keep UIA_Browser at least semi-useful with it. I'm not exactly sure when, but at some point Firefox became SUPER slow with UIA. For example, try inspecting Reddit in it with UIAViewer or Accessibility Insights, and you'll see that the inspect tool freezes for a bit and is generally super sluggish. I don't remember it being that way a few months back...

The good news is that in Firefox 110 it should be much much faster: https://www.ghacks.net/2022/12/26/firefoxs-accessibility-performance-is-getting-a-huge-boost/
I tried Firefox 110 beta 5, and can confirm that UIA is fixed there: everything is snappy, and loading UIA_Browser takes about 500ms (to load all the elements for Document, AddressBar etc). Could you test it out as well?

**Comment by enaaab460** [comment]
> Hello, I don't use Firefox regularly, but I do try to keep UIA_Browser at least semi-useful with it. I'm not exactly sure when, but at some point Firefox became SUPER slow with UIA. For example, try inspecting Reddit in it with UIAViewer or Accessibility Insights, and you'll see that the inspect tool freezes for a bit and is generally super sluggish. UIA should NOT be that slow even with HUGE trees! And I don't remember it being that slow a few months back, I wonder if they changed something?
> 
> The good news is that in Firefox 110 it should be much much faster: https://www.ghacks.net/2022/12/26/firefoxs-accessibility-performance-is-getting-a-huge-boost/ I tried Firefox 110 beta 5, and can confirm that UIA is fixed there: everything is snappy, and loading UIA_Browser takes about 500ms (to load all the elements for Document, AddressBar etc). Could you test it out as well?

Can confirm UIA is much faster with Firefox 110 beta 5, (but devtools still takes a second to load,albeit much faster than before). Thanks for the response!

**Comment by Descolada** [comment]
I implemented your proposed performance optimizations. Also added an option to create UIA_Mozilla with the javascriptFromBookmark argument, which will cause JSExecute to run javascript with the "javascript:%s" bookmark instead of the console. The user will have to set it up themselves though.
