### ISSUE TITLE
Rare stuck opening browser

### ISSUE THREAD

**Issue by mora145** [Descolada/UIAutomation#34]
Greetings Descolada. 

I have a recurring problem where after running this Code, it gets stuck before opening the new window to go to the web. I already updated the libraries and still the same problem. 
```
#NoEnv
#include <UIA_Browser>
#SingleInstance, Force
SendMode, Input
SetBatchLines, -1
SetWorkingDir, %A_ScriptDir%

;DEFINITIONS - BUTTONS NAME
moreButton:="לצפייה ברשימה המלאה"
phoneButton:="דברו איתי"
nextPageText:="הבא"

;Create a new UIA interface and a new UIA_Browser object
UIA := UIA_Interface()
browserExe := "chrome.exe"

;Run the browser and force accessibility in case its disabled by default.
Run, %browserExe% --force-renderer-accessibility ;
Sleep, 5000
WinWaitActive, ahk_exe %browserExe%
chromeId := WinExist("ahk_exe chrome.exe")
cUIA := new UIA_Browser("ahk_exe" browserExe)

;Open a new tab
cUIA.NewTab()
cUIA.WaitPageLoad()
cUIA.SetURL("https://www.google.com", True)
cUIA.WaitPageLoad()
```

The log look like this...
![Screenshot_26](https://user-images.githubusercontent.com/25883820/215303644-e8193123-52ba-414a-9f1a-1515ae463030.jpg)

**Comment by Descolada** [comment]
I've had that problem if the browser window I'm trying to hook onto with UIA_Browser is not visible. It gets stuck looking for the Document element, which it can't find if it's not visible on the screen. Could you test whether 
```
WinWaitActive, ahk_exe %browserExe%
cUIA := new UIA_Browser("A")
```
fixes the issue?

**Comment by mora145** [comment]
OK ok. Let me check.

**Comment by mora145** [comment]
So far it has worked, it has not stuck again.
