### ISSUE TITLE
Recurring error UIA_E_ELEMENTNOTAVAILABLE

### ISSUE THREAD

**Issue by mora145** [Descolada/UIAutomation#35]
Hello. 
I recurrently get this error. I'm trying to click on a button, sometimes it does, but 10% I get this error.

![Screenshot_33](https://user-images.githubusercontent.com/25883820/215587870-93baf533-51aa-4198-9953-c2914a4aa19e.jpg)

**Comment by Descolada** [comment]
I updated UIA_Browser.ahk just now - could you try and see if it still persists?

**Comment by mora145** [comment]
Ok, cheking

**Comment by Descolada** [comment]
@mora145 can I close the issue?

**Comment by mora145** [comment]
Ye, is solved :)
