### ISSUE TITLE
New UI 

### ISSUE THREAD

**Issue by samfisherirl** [Descolada/UIAutomation#37]
Tell me what you think. Functions and Design. I was going to do neutron but that's more time than I have atm. 
 
![image](https://user-images.githubusercontent.com/98753696/219832219-fcbd1f99-05ae-4dbc-8b22-388804bd9553.png)

**Comment by Descolada** [comment]
Added comments/issues in your repo about this.
For some reason the GUI in this screenshot looks a lot nicer than the one I get in Windows 10 :/
