### ISSUE TITLE
UIA with autohotkey_h

### ISSUE THREAD

**Issue by henriqueterada** [Descolada/UIAutomation#42]
Hello Descolada,
I´m trying to run the UIA script with autohotkey_h, but I´m getting some issues. Most are about the ? as  optional parameter in a function. Trying to make some amends, by myself, but just thought, do you have plans to make it compatible with autohotkey_H ?

Thanks,
Henrique

**Comment by henriqueterada** [comment]
I´m running v2 , by the way

**Comment by Descolada** [comment]
Hello,
I currently have no plans of "supporting" AHK_H, because AHK_H is supposed to be compatible with AHK_L, so no support should be necessary. Perhaps open an issue with AHK_H instead?
Also you are posting in the AHK v1 library repo. For v2 there is the UIA-v2 repo.

**Comment by henriqueterada** [comment]
Thanks for clarifying. And sorry for posting in the wrong place. Didn't ser that.

HT
Em 13 de mai. de 2023 00:37 -0300, Descolada ***@***.***>, escreveu:
