### ISSUE TITLE
Can't set Value

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [Descolada/UIAutomation#43]
Hello Descolada,
I ran the `Example1_Notepad.ahk` but the document control did not change. I am using `Windows 11 21H2` and `AutoHotkey 1.1.36.2`

![图片](https://github.com/Descolada/UIAutomation/assets/14090545/03d63e1d-d049-4309-bdba-d0aded279f21)

**Comment by LakeishaKowalczyk** [comment]
@Descolada 
Thank you, It works like a charm.
And the button click speed is a bit slow, about once every 2 seconds. Is there a way to speed it up?

**Comment by Descolada** [comment]
What do you mean by "button click speed"? What button are you talking about?

**Comment by LakeishaKowalczyk** [comment]
@Descolada 
I mean that when running Example2_Notepad.ahk, there is about 2 seconds of waiting time before clicking on 'File' and 'Save'.

**Comment by Descolada** [comment]
That is by design - Highlight() pauses and highlights the element for two seconds. Remove the highlight commands to make it faster, eg remove the line with `fileEl.Highlight()`.

**Comment by LakeishaKowalczyk** [comment]
@Descolada 
Thank you very much
