### ISSUE TITLE
How to prevent throw? 

### ISSUE THREAD

**Issue by Skrell** [Descolada/UIAutomation#46]
I'm not sure what is causing this issue nor am I sure if it's truly fatal, is there anything I can filter out class/window wise to prevent it from happening?  
![image](https://github.com/Descolada/UIAutomation/assets/590266/2c69eaba-6dfa-42d7-a572-c92321065b5b)

**Comment by Descolada** [comment]
You can wrap whatever is causing it in a `try-catch` block ;) Can you provide a reproducible example of what causes it?

**Comment by Skrell** [comment]
> You can wrap whatever is causing it in a `try-catch` block ;) Can you provide a reproducible example of what causes it?

I cannot unfortunately.  I'm pretty sure it has something to do with my newly installed Start11 v2 application from Stardock bc it never happened before then.  

Where would I place the try/catch?  
Inside the UIA_Hr(hr) constructor or around lines 3866 where the constructor is called?

**Comment by Descolada** [comment]
No, you use it on whatever call in your written code is causing it. Eg `FindFirstBy` or `Click` or...

Btw I strongly recommend switching to AHK v2 and UIA-v2. There, among other things, you can better see what exactly is throwing the error.

**Comment by Skrell** [comment]
So turns out I already had try/catch implemented there and I still get the error?

```
ButCapture:
    If (GetKeyState("RButton", "P") || GetKeyState("MButton", "P") || (mtClass == "WorkerW")  || (mtClass == "Progman") || (mtClass == "Shell_TrayWnd") || (mtClass == "SALFRAME"))
    {
        Return
    }

    WinGet, winExe, ProcessName, %winId%
    WinGetTitle, winTitle, %winId%
    If (!SkipElementFromPos && winExe != "Spotify.exe")
    {
        try {
               If (mtClass == "Chrome_WidgetWin_1" && winTitle != "Messages for web")
               {
                    mEl := UIA.SmallestElementFromPoint(MXw, MYw, True, UIA.ElementFromHandle(winId))
               }
               Else If (winExe == "notepad++.exe")
               {
                    mEl := UIA.ElementFromPoint(MXw, MYw)
               }
               Else If (winTitle)
               {
                    mEl := UIA.SmallestElementFromPoint(MXw, MYw, True, "")
               }
               Else
               {
                   mEl := UIA.ElementFromPoint(MXw, MYw)
               }
            } catch e {
            }
    }
    Else
    {
       try {
            If InStr(mEl.CurrentName, "Close")
            {
                BASS_Play(Sound_Close, 0.25)
                removeId  := False
                removeIdx := 0

                for idx, val in PeaksArray {
                  If (val == winId) {
                      WinSet, AlwaysOnTop, Off, %winId%
                      LookForLeaveWindow := False
                      removeId           := True
                      removeIdx          := idx
                      Break
                     }
                  }

                If removeId
                {
                    PeaksArray.remove(removeIdx)
                    WinBackupXs.remove("hwnd" . mHwnd)
                    LastRemovedWinHwnd :=mHwnd
                    ForceButtonRemove  := True
                }

                i := 1
                for idx, savedID in ExplorerArrayIds
                {
                    If (savedID == winHwnd)
                    {
                        ExplorerArrayIds.Remove(i)
                        break
                    }
                    ++i
                }
                mEl := {}
            }
            Else If InStr(mEl.CurrentName, "Maximize")
            {
                mEl := {}
            }
            Else If InStr(mEl.CurrentName, "Minimize")
            {
                mEl := {}
            }
        } catch e {
        }
        SkipElementFromPos := False
    }
Return
```

**Comment by Skrell** [comment]
Nm, figured it out!  Now I don't get a throw message, but instead explorer itself actually crashes and restarts.... odd but still improvement.

**Comment by Descolada** [comment]
Interesting... UIA shouldn't crash the inspected applications, so I'm still interested in reproducing the bug and please let me know if you figure out which call is causing it. The bug might even be caused by something on Microsofts side.

**Comment by Skrell** [comment]
I'm almost certain this issue is related to the taskbar and since I recently installed Start11 v2 I'm thinking it's  also related to that.  

I plan to find some time soon to use your UIA viewer on the taskbar to see if that provokes the crash of explorer.exe (or maybe it's literally crashing start11's exe; hard to tell because the entire taskbar restarts when it happens as if explorer crashes but I could be wrong)

**Comment by Descolada** [comment]
@Skrell Have you managed to reproduce the issue?

**Comment by Skrell** [comment]
Turns out it was in fact Start11v2's fault!

**Comment by Skrell** [comment]
See last comment
