### ISSUE TITLE
Can't access the UIAViewer path options

### ISSUE THREAD

**Issue by soticoker** [Descolada/UIAutomation#47]
Hi Descolada, 
Great library and thanks for creating!
However when I use the UIAViwer.ahk, I can't access the "multiple types of paths available to travel to elements", 
according to this page : https://github.com/Descolada/UIA-v2/wiki/01.-Getting-started#uia-paths
I should be able to toggle between them by right-clicking on the status bar at the bottom. 
But when I right click on the status bar, the only option I have is 
"Click here to enable aces heap of capturing(can't be used with UIA!)" ?
Many Thanks
Soti

**Comment by Descolada** [comment]
You linked the wiki for UIA-v2 which is the library for AHK v2 and has a separate UIAViewer (run UIA.ahk alone to show it). This here is the library for AHK v1 and doesn't have the UIA paths available (and no plans to add them).
