### ISSUE TITLE
Input Is Being Ignored for a Split Second Right After using .Click()

### ISSUE THREAD

**Issue by ars4l4n** [Descolada/UIAutomation#52]
I'm using a script that clicks the YouTube searchfield for me automatically as soon as I start entering a search term.

I'm having a problem with it, however: If I type too quickly, some of the input is being ignored, meaning, there's some downtime after the .Click() on the searchfield in line 13.
How do I fix that?

Here's an excerpt of the script to showcase the issue:

```
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines, -1
#include .\UIAutomation-main\Lib\UIA_Interface.ahk
UIA := UIA_Interface()

WinWaitActive YouTube ahk_exe chrome.exe ; Wait for YouTube to be the active window.
ih := InputHook("V", alphanumeric := "abcdefghijklmnopqrstuvwxyz0123456789") ; Then, wait for an input of an alphanumeric character.
ih.KeyOpt(alphanumeric, "S")
ih.Start(), ih.Wait()
YouTube := UIA.ElementFromHandle("YouTube - Google Chrome ahk_exe chrome.exe")
YouTube.WaitElementExist("ControlType=ComboBox AND AutomationId='search'").Click() ; alphanumerical character entered? -> click the searchfield
Send, % ih.EndKey ; type said alphanumerical character into the searchfield
```

I also tried `ControlClick(WinTitleOrSleepTime)=""`, `.SetFocus()` and `.Value :=` as alternatives to `.Click` but they have the same problem. I'm having a similar problem when using `.Focus()` in JS via Chrome.ahk or when using `FindFirstBy `instead of `WaitElementExist `. Only AHK's `ControlClick` has a rather low delay, but isn't as practical as the other variants.

**Comment by Descolada** [comment]
The problem is that none of those methods wait until the action is complete. For example `Click()` tells Chrome to invoke the combobox and then immediately continues on to sending the text without waiting for the combobox to actually focus. You need to add a small delay if you want to send keys into the combobox field, but that doesn't solve the problem of keys being missed in the meanwhile. You would need to implement keystroke buffering for the duration of the delay and then resend the keys afterwards, but that is outside the scope of UIA.

**Comment by Descolada** [comment]
Maybe this will help you along:
```
#Requires Autohotkey v1
#NoEnv
SetWorkingDir %A_ScriptDir%
global g_BufferedKeys := []

SetBatchLines, -1
#include .\UIAutomation-main\Lib\UIA_Interface.ahk
UIA := UIA_Interface()

WinWaitActive YouTube ahk_exe chrome.exe ; Wait for YouTube to be the active window.
ih := InputHook("V", alphanumeric := "abcdefghijklmnopqrstuvwxyz0123456789") ; Then, wait for an input of an alphanumeric character.
ih.KeyOpt(alphanumeric, "S")
ih.Start(), ih.Wait()
g_BufferedKeys := [{VK:GetKeyVK(ih.EndKey), SC:GetKeySC(ih.EndKey)}]
BufferInput()
YouTube := UIA.ElementFromHandle("YouTube - Google Chrome ahk_exe chrome.exe")
YouTube.WaitElementExist("ControlType=ComboBox AND AutomationId='search'").Click() ; alphanumerical character entered? -> click the searchfield
Sleep 200
BufferInput(0)

BufferInput(start:=1) {
    static ih := ""
    if (start) {
        if (!ih) {
            ih := InputHook("L0 I1") ; no limit; ignore SendLevel < 1 (prevents recursion)
            ih.KeyOpt("{All}", "N")
            ih.OnKeyDown := Func("BufferInputOnKeyDown")
        }
        ih.Start()
    } else {
        While g_BufferedKeys.Count()
        {
            Key := g_BufferedKeys.RemoveAt(1) ; pop front
            Send % Format("{vk{:02X}sc{:03X}}", Key.VK, Key.SC)
        }
        ih.Stop()
    }
}

BufferInputOnKeyDown(InputHook, VK, SC) {
	g_BufferedKeys.Push({VK: VK, SC: SC})
}
```

**Comment by ars4l4n** [comment]
@Descolada Thanks for your effort. For some reason, what you did with the script causes it to not do anything anymore, though. Not even `WinWaitActive` works. I tested that by putting a `MsgBox` below it.

**Comment by Descolada** [comment]
In that case something else in your code is going wrong. `WinWaitActive YouTube ahk_exe chrome.exe` shouldn't hang because all the relevant changes are *after* that line.

**Comment by ars4l4n** [comment]
> In that case something else in your code is going wrong. `WinWaitActive YouTube ahk_exe chrome.exe` shouldn't hang because all the relevant changes are _after_ that line.

But the version from my OP did work as I described. Is the version you wrote working for you? To test it, go on YouTube, enter a letter and see if that causes the searchbar to be focused.

**Comment by Descolada** [comment]
I tested again and `WinWaitActive` was not getting stuck. However, `YouTube.WaitElementExist` was getting stuck. It turns out that YouTube search bar sometimes is a ComboBox type and sometimes Edit type, I guess when I was first testing it then it happened to only be ComboBox. Changing that line to `YouTube.WaitElementExist("Type=ComboBox OR Type=Edit AND AutomationId='search'").Click()` fixed the issue.

**Comment by ars4l4n** [comment]
You're right and now it's fixed for me.

**Comment by ars4l4n** [comment]
There was some unexpected behaviour in my script after I added back some of the code I removed for simplification. My script originally contained a section to allow for Ctrl V inputs to be treated as Paste. After putting the script together, however, it only sends the character "v" whenever I Ctrl V into a searchfield. And I can't figure out how to fix that.


```
; rest of the code
ih.Start(), ih.Wait()
g_BufferedKeys := [{VK:GetKeyVK(ih.EndKey), SC:GetKeySC(ih.EndKey)}]
BufferInput()
YouTube := UIA.ElementFromHandle("YouTube - Google Chrome ahk_exe chrome.exe")
If (GetKeyState("Ctrl", "P") && ih.EndKey = "v"){
 YouTube.WaitElementExist("Type=ComboBox OR Type=Edit AND AutomationId='search'").Click()
 Send ^v
}
Else {YouTube.WaitElementExist("Type=ComboBox OR Type=Edit AND AutomationId='search'").Click()
 Send, % ih.EndKey
}
Sleep 200
BufferInput(0)
; rest of the code

```
