### ISSUE TITLE
WaitElement throws an Error instead of working

### ISSUE THREAD

**Issue by ars4l4n** [Descolada/UIAutomation#55]
I'd like to fire a MsgBox, once an element with certain properties is found. To do that, I tried `if (foundElement := el.WaitElement({Name:"Formatierungsoptionen anzeigen" })) {`.
```
#include C:\Users\arsi\Documents\AutoHotkey\Lib\UIAutomation-main\Lib\UIA_Interface.ahk
UIA := UIA_Interface()


SetTitleMatchMode, 2
WinWaitActive, - Google Chrome

el := UIA.ElementFromHandle(el)
if (foundElement := el.WaitElement({Name:"Formatierungsoptionen anzeigen" })) {
	MsgBox, element found
}
```

Running the code above throws this error:
![AutoHotkey_2024-08-07_15-04-40](https://github.com/user-attachments/assets/ea3d7d1a-f93e-4c84-94a5-3048126307fe)

Also, I actually want to check for several properties of the element to match, like this:

`if (foundElement := el.WaitElement({ControlType:"Button" AND Name:"Formatierungsoptionen anzeigen" })) {`

which doesn't even execute and just throws this error in the code editor: C:\Users\arsi\Desktop\Autohotkey Scripts\1) fertige\Reddit Strg+K - Link einfügen\test4.ahk (9) : ==> Missing "key:" in object literal.

How do I fix this?

**Comment by Descolada** [comment]
You are combining AHK v1 UIA_Interface syntax with AHK v2 UIA syntax. In v1 there is no such method `WaitElement` and the object notation with {} can't be used. The v1 equivalent would be `el.WaitElementExist("Name=Formatierungsoptionen anzeigen")`
