### ISSUE TITLE
WaitNotExist

### ISSUE THREAD

**Issue by tgdonovan** [Descolada/UIAutomation#9]
Would like to recommend adding the WaitElementNotExist (WaitElementExist equivalents). I have implemented and find them very helpful. So far just removing the ! (not) seems to do the trick

**Comment by Descolada** [comment]
Hey,
Thanks for the suggestion! Hadn't needed it myself yet, but UIA probably needs a way of checking if the element exists anyway... I will include these in the next version:
`	CurrentExists[] {
		get {
			try {
				if ((val := this.CurrentName this.CurrentValue (this.CurrentBoundingRectangle.t ? 1 : "")) == "")
					return 0
			} 
			return 1
		}
	}
	WaitNotExist(timeOut=10000) { ; Wait until the element doesn't exist, with a default timeOut of 10000ms (10 seconds). Returns 1 if the element doesn't exist, otherwise 0.
		startTime := A_TickCount
		while ((exists := this.CurrentExists) && ((timeOut < 1) ? 1 : (A_tickCount - startTime < timeOut)))
			Sleep, 100
		return !exists
	}`

So you could do
`If !(el := windowEl.FindFirstBy("...")) || el.WaitNotExist()`
